import 'package:e_commerce_provider/models/products_model.dart';

class MyProducts {
  static List<Product> allProducts = [
    Product(
        name: "New Jacket",
        image: 'assets/jackets_pictures/jacket1.png',
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 1,
        quantity: 1,
        category: 'Trending Now'),
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers1.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Out Of Stock'),
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers2.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Shoes'),
    Product(
        name: "New Jacket",
        image: "assets/jackets_pictures/jacket2.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Shoes'),
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers3.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Shoes'),
    Product(
        name: "New Jacket",
        image: "assets/jackets_pictures/jacket3.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Jacket'),
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers4.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Shoes'),
    Product(
        name: "New Jacket",
        image: "assets/jackets_pictures/jacket4.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Out Of Stock'),
  ];

  static List<Product> sneakersList = [
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers1.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Out Of Stock'),
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers2.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Shoes'),
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers3.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Shoes'),
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers4.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Shoes'),
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers5.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Shoes'),
    Product(
        name: "New Sneakers",
        image: "assets/sneakers_pictures/sneakers6.png",
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Shoes'),
  ];

  static List<Product> jacketsList = [
    Product(
        name: "New Jacket",
        image: 'assets/jackets_pictures/jacket1.png',
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 1,
        quantity: 1,
        category: 'Jacket'),
    Product(
        name: "New Jacket",
        image: 'assets/jackets_pictures/jacket2.png',
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 2,
        quantity: 1,
        category: 'Jacket'),
    Product(
        name: "New Jacket",
        image: 'assets/jackets_pictures/jacket3.png',
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 3,
        quantity: 1,
        category: 'Jacket'),
    Product(
        name: "New Jacket",
        image: 'assets/jackets_pictures/jacket4.png',
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 4,
        quantity: 1,
        category: 'Out Of Stock'),
    Product(
        name: "New Jacket",
        image: 'assets/jackets_pictures/jacket5.png',
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 4,
        quantity: 1,
        category: 'Out Of Stock'),
    Product(
        name: "New Jacket",
        image: 'assets/jackets_pictures/jacket6.png',
        description: "dlawejrt ads fdsofg df asdfd",
        price: 120,
        id: 4,
        quantity: 1,
        category: 'Out Of Stock'),
  ];
}
